POST http://localhost:8000/products
Content-Type: application/json

{
    "name": "Product {{$randomInt}}",
    "price": {{$random.float}}
}

###

GET http://localhost:8000/products/2ac0f761-fb5a-455d-a57d-806ceec4cc55
Content-Type: application/json

###

PATCH http://localhost:8000/products/2ac0f761-fb5a-455d-a57d-806ceec4cc55
Content-Type: application/json

{
    "name": "Product {{$randomInt}}",
    "price": {{$random.float}}
}

###

GET http://localhost:8000/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDE4MTk0MDUsInN1YiI6IjRkMGMwYmY5LTljZGMtNDA3ZC1hZWY2LTc2NjYwMzFkNjFkYiJ9.99TrTxnhibJeuBfTEANF6HS4rxNUslhLsjR3VO5JTX0

###

DELETE http://localhost:8000/products/2ac0f761-fb5a-455d-a57d-806ceec4cc55
Content-Type: application/json
