// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/busca-cep/{cep}": {
            "get": {
                "description": "Find a cep",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cep"
                ],
                "summary": "Find a cep",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Cep",
                        "name": "cep",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_SCHUGRWS_fullcycle-posgoexpert-desafio2_internal_dto_webserver.FindCepResponseDto"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_SCHUGRWS_fullcycle-posgoexpert-desafio2_internal_dto.Error"
                        }
                    },
                    "408": {
                        "description": "Request Timeout",
                        "schema": {
                            "$ref": "#/definitions/github_com_SCHUGRWS_fullcycle-posgoexpert-desafio2_internal_dto.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_SCHUGRWS_fullcycle-posgoexpert-desafio2_internal_dto.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_SCHUGRWS_fullcycle-posgoexpert-desafio2_internal_dto.Error": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_SCHUGRWS_fullcycle-posgoexpert-desafio2_internal_dto_client.CepClientResponseDto": {
            "type": "object",
            "properties": {
                "bairro": {
                    "type": "string"
                },
                "cep": {
                    "type": "string"
                },
                "cidade": {
                    "type": "string"
                },
                "complemento": {
                    "type": "string"
                },
                "logradouro": {
                    "type": "string"
                },
                "uf": {
                    "type": "string"
                }
            }
        },
        "github_com_SCHUGRWS_fullcycle-posgoexpert-desafio2_internal_dto_webserver.FindCepResponseDto": {
            "type": "object",
            "properties": {
                "api-origem": {
                    "type": "string"
                },
                "dados-endereco": {
                    "$ref": "#/definitions/github_com_SCHUGRWS_fullcycle-posgoexpert-desafio2_internal_dto_client.CepClientResponseDto"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "GO Expert Desafio 2",
	Description:      "This is a cep finder API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
